---
title: "check weights diff, xin and seger"
author: "DongyueXie"
date: "2021-03-22"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r,message=F,warning=F}
library(MuSiC)
library(Biobase)
library(xbioc)
source('code/deconference_main.R')
source('code/utils.R')
seger <- readRDS("~/deconference/data/pancreas/segerstolpe_raw.rds")
refs_raw <- readRDS("~/deconference/data/pancreas/refs_raw.rds")
genes = rownames(refs_raw$xin)

XinT2D.eset <- readRDS("data/MuSiC/XinT2Deset.rds")
XinT2D.construct.full = bulk_construct(XinT2D.eset, clusters = 'cellType', samples = 'SubjectName')
XinT2D.construct.full$prop.real = relative.ab(XinT2D.construct.full$num.real, by.col = FALSE)
```

```{r}
xin_raw <- readRDS("~/deconference/data/pancreas/xin_raw.rds")

bulk.indi = c(4,7,10,12)
bulk.indi = levels(XinT2D.eset$SubjectName)[bulk.indi]
bulk.idx = which(XinT2D.eset$SubjectName%in%bulk.indi)
Est.prop.xin = music_prop(XinT2D.construct.full$Bulk.counts,XinT2D.eset[,-bulk.idx],
                          clusters = 'cellType', samples = 'SubjectName', 
                          markers = genes,
                          select.ct =  c('alpha', 'beta', 'delta', 'gamma'),verbose = FALSE)
cell_types = c('alpha', 'beta', 'delta', 'gamma')
K = length(cell_types)
datax = set_data_decon(exprs(XinT2D.construct.full$Bulk.counts),
                       xin_raw[,-bulk.idx],marker_gene = rownames(Est.prop.xin$Weight.gene),
                       cell_types = cell_types, gene_thresh = 0,max_count_quantile = 1,w=1)

design.mat.xin = scRef_multi_proc(datax$Y,datax$cell_type_idx,datax$indi_idx,estimator="separate",est_sigma2 = FALSE,
                                    meta_var='plug_in',meta_mode='smooth',
                                    verbose = TRUE)

datax = set_data_decon(exprs(XinT2D.construct.full$Bulk.counts),
                       seger,marker_gene = rownames(Est.prop.xin$Weight.gene),
                       cell_types = cell_types, gene_thresh = 0,max_count_quantile = 1,w=1)

design.mat.seger = scRef_multi_proc(datax$Y,datax$cell_type_idx,datax$indi_idx,estimator="separate",est_sigma2 = FALSE,
                                    meta_var='plug_in',meta_mode='smooth',
                                    verbose = TRUE)
```


Look at how difference the weights obtained from xin and seger dataset.

## Equal $\beta$:

```{r}
Sigma_sample_xin = c()
idx.xin = 1:dim(design.mat.xin$X_array)[3]
idx.xin = idx.xin[-c(4,7,10,12)]
for(i in idx.xin){
  Sigma_sample_xin = cbind(Sigma_sample_xin,(design.mat.xin$X_array[,,i] - design.mat.xin$X)%*%rep(1/K,K))
}
cov.xin = Rfast::cova(t(Sigma_sample_xin))
d.xin = sqrt(diag(cov.xin))
```

```{r}
Sigma_sample_seger = c()
idx = 1:dim(design.mat.seger$X_array)[3]
#idx = idx[-c(4,7,10,12)]
for(i in idx){
  Sigma_sample_seger = cbind(Sigma_sample_seger,(design.mat.seger$X_array[,,i] - design.mat.seger$X)%*%rep(1/K,K))
}
cov.seger = Rfast::cova(t(Sigma_sample_seger))
d.seger = sqrt(diag(cov.seger))
```

```{r}
cor(d.xin,d.seger)
plot(d.xin,d.seger,ylim = c(0,20),xlim=c(0,20))
```


## True bulk $\beta$ but we use equal weights.

```{r}
datax = set_data_decon(exprs(XinT2D.construct.full$Bulk.counts),
                       xin_raw[,-bulk.idx],marker_gene = rownames(Est.prop.xin$Weight.gene),
                       cell_types = cell_types, gene_thresh = 0,max_count_quantile = 1,w=1)

d.true = matrix(nrow=nrow(datax$y),ncol = ncol(datax$y))
for(j in 1:ncol(d.true)){
  Sigma_sample = c()
   for(i in idx.xin){
    Sigma_sample = cbind(Sigma_sample,
                         (design.mat.xin$X_array[,,i] - design.mat.xin$X)%*%as.numeric(XinT2D.construct.full$prop.real[j,]))
   }
   cov.Xb = Rfast::cova(t(Sigma_sample))
   #print(range(diag(cov.Xb)))
   d = sqrt(diag(cov.Xb))
   d.true[,j] = d
}
```

```{r}
round(apply(d.true, 2, cor,d.seger),3)
```


## True $\beta$ and we use true $\beta$.


```{r}
d.true.seger = matrix(nrow=nrow(datax$y),ncol = ncol(datax$y))
for(j in 1:ncol(d.true.seger)){
  Sigma_sample = c()
   for(i in idx){
    Sigma_sample = cbind(Sigma_sample,
                         (design.mat.seger$X_array[,,i] - design.mat.seger$X)%*%as.numeric(XinT2D.construct.full$prop.real[j,]))
   }
   cov.Xb = Rfast::cova(t(Sigma_sample))
   #print(range(diag(cov.Xb)))
   d = sqrt(diag(cov.Xb))
   d.true.seger[,j] = d
}
```

```{r}
round(diag(cor(d.true,d.true.seger)),3)
```

```{r}
plot(d.true[,1],d.true.seger[,1],ylim = c(0,20),xlim=c(0,20))
```
