---
title: "gene Correlation"
author: "DongyueXie"
date: "2020-11-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---



```{r}
source('code/deconference_main.R')
source('code/corr_mat_prune.R')
library(sandwich)
X_xin = readRDS("data/pancreas/X_xin.rds")
refs_raw = readRDS("data/pancreas/refs_raw.rds")
simu_result = function(X,beta){
  
  y <- apply(X, 3, function(mat) mat %*% beta)
mu <- rowMeans(X, dims = 2)

rm.idx = which(rowSums(mu)==0)


est.beta <- apply(y, 2, function(v) {
  temp <- lm(v ~ mu + 0)
  sw.sd <- sqrt(diag(vcovHC(temp, type="HC3")))
  std.sd <- sqrt(diag(vcov(temp)))
  temp <- pmax(temp$coef, 0)
  return(signif(c(temp/sum(temp), (temp - beta) / std.sd, (temp - beta) / sw.sd), 2))
})
rownames(est.beta) <- c("Est1", "Est2", "Est3", "dev1.OLS", "dev2.OLS", "dev3.OLS", "dev1.sandwich", "dev2.sandwich", "dev3.sandwich")
MSE <- signif(sqrt(colSums((est.beta[1:3, ] - beta)^2)), 1)
print(rbind(est.beta, MSE))

}
```


# Xin

## all gene

```{r}
X <- X_xin$X_array[, , -c(4, 7)]
beta <- c(0.2, 0.3, 0.5) ## true beta for every one
simu_result(X,beta)
```

## all gene permute

```{r}
set.seed(12345)
X.perm <- X
for (i in 1:nrow(X))
  X.perm[i, , ] <- X.perm[i, , sample.int(16)]

simu_result(X.perm,beta)
```



# Segerstople

```{r}
X_seger = getXV_array(counts(refs_raw$seger),cell_type_idx = refs_raw$seger$cell_type,indi_idx = refs_raw$seger$individual,cell_types = c('alpha','beta','delta'))
```

## all gene

```{r}
X <- X_seger$X_array
simu_result(X,beta)
```

## all gene permute

```{r}
set.seed(12345)
X.perm <- X
for (i in 1:nrow(X))
  X.perm[i, , ] <- X.perm[i, , sample.int(dim(X)[3])]

simu_result(X.perm,beta)
```

# enge

```{r}
X_enge = getXV_array(counts(refs_raw$enge),cell_type_idx = refs_raw$enge$cell_type,indi_idx = refs_raw$enge$individual,cell_types = c('alpha','beta','delta'))
```

## all gene

```{r}
X <- X_enge$X_array[,,-8]
simu_result(X,beta)
```

## all gene permute

```{r}
set.seed(12345)
X.perm <- X
for (i in 1:nrow(X))
  X.perm[i, , ] <- X.perm[i, , sample.int(dim(X)[3])]

simu_result(X.perm,beta)
```


# Baron

```{r}
X_baron = getXV_array(counts(refs_raw$baron),cell_type_idx = refs_raw$baron$cell_type,indi_idx = refs_raw$baron$individual,cell_types = c('alpha','beta','delta'))
```

## all gene

```{r}
X <- X_baron$X_array
simu_result(X,beta)
```

## all gene permute

```{r}
set.seed(12345)
X.perm <- X
for (i in 1:nrow(X))
  X.perm[i, , ] <- X.perm[i, , sample.int(dim(X)[3])]

simu_result(X.perm,beta)
```


# Muraro

```{r}
X_muraro = getXV_array(counts(refs_raw$muraro),cell_type_idx = refs_raw$muraro$cell_type,indi_idx = refs_raw$muraro$individual,cell_types = c('alpha','beta','delta'))
```

## all gene

```{r}
X <- X_muraro$X_array
simu_result(X,beta)
```

## all gene permute

```{r}
set.seed(12345)
X.perm <- X
for (i in 1:nrow(X))
  X.perm[i, , ] <- X.perm[i, , sample.int(dim(X)[3])]

simu_result(X.perm,beta)
```


# gene correlation

```{r}
# all_counts = c()
# for(i in 1:5){
#   all_counts = rbind(all_counts,t(counts(refs_raw[[i]])))
# }
# all_counts = log((all_counts+0.01)/rowSums(all_counts+0.01)*1e6)
# gene_cor = cor(all_counts)
gene_cor = readRDS('data/pancreas/gene_cor.rds')
selected_gene1000 = corr_matrix_prune(gene_cor,n_var = 1000)
selected_gene500 = corr_matrix_prune(gene_cor,n_var = 500)
selected_gene100 = corr_matrix_prune(gene_cor,n_var = 100)
selected_gene50 = corr_matrix_prune(gene_cor,n_var = 50)
```

## Xin

### 1000

```{r}
simu_result(X_xin$X_array[selected_gene1000, , -c(4, 7)],beta)
```

### 500

```{r}
simu_result(X_xin$X_array[selected_gene500, , -c(4, 7)],beta)
```

### 100

```{r}
simu_result(X_xin$X_array[selected_gene100, , -c(4, 7)],beta)
```

### 50

```{r}
simu_result(X_xin$X_array[selected_gene50, , -c(4, 7)],beta)
```


## Seger

### 1000

```{r}
simu_result(X_seger$X_array[selected_gene1000, , ],beta)
```

### 500

```{r}
simu_result(X_seger$X_array[selected_gene500, , ],beta)
```

### 100

```{r}
simu_result(X_seger$X_array[selected_gene100, , ],beta)
```

### 50

```{r}
simu_result(X_seger$X_array[selected_gene50, , ],beta)
```



## enge

### 1000

```{r}
simu_result(X_enge$X_array[selected_gene1000, , -8],beta)
```

### 500

```{r}
simu_result(X_enge$X_array[selected_gene500, , -8],beta)
```

### 100

```{r}
simu_result(X_enge$X_array[selected_gene100, , -8],beta)
```

### 50

```{r}
simu_result(X_enge$X_array[selected_gene50, , -8],beta)
```

# baron

### 1000

```{r}
simu_result(X_baron$X_array[selected_gene1000, , ],beta)
```

### 500

```{r}
simu_result(X_baron$X_array[selected_gene500, , ],beta)
```

### 100

```{r}
simu_result(X_baron$X_array[selected_gene100, , ],beta)
```

### 50

```{r}
simu_result(X_baron$X_array[selected_gene50, , ],beta)
```

# muraro

### 1000

```{r}
simu_result(X_muraro$X_array[selected_gene1000, , ],beta)
```

### 500

```{r}
simu_result(X_muraro$X_array[selected_gene500, , ],beta)
```

### 100

```{r}
simu_result(X_muraro$X_array[selected_gene100, , ],beta)
```

### 50

```{r}
simu_result(X_muraro$X_array[selected_gene50, , ],beta)
```
