---
title: "Check variance estimate ,when correlation presents "
author: "DongyueXie"
date: "2021-06-15"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r,warning=F,message=F}
source('code/deconference_main.R')
source('code/utils.R')
source('code/wols.R')
source('code/simulation/simu_correlation.R')

ploter.temp = function(results){

  par(mfrow=c(2,2))

  plot(results$coverage_adj_hc0,
       ylim = range(c(results$coverage_adj_hc0,results$coverage_unadj_hc0,results$coverage_unadj_cv,1),na.rm = T),
       col=2,ylab='coverage',xlab='coefs',main='coverage of p',type='b')
  lines(results$coverage_unadj_hc0,type='b',pch=2,col=4)
  lines(results$coverage_unadj_cv,type='b',pch=2,col=3)
  abline(h=0.95,lty=2)

  plot(results$coverage_diff_adj_hc0,ylim = range(c(results$coverage_diff_adj_hc0,results$coverage_diff_unadj_hc0,results$coverage_diff_unadj_cv,1),na.rm = T),
       col=2,type='b',ylab='coverage',xlab='coefs',main='coverage of difference')
  lines(results$coverage_diff_unadj_hc0,type='b',pch=2,col=4)
  lines(results$coverage_diff_unadj_cv,type='b',pch=2,col=3)
  abline(h=0.95,lty=2)

  #p_order = order(abs(results$p-results$p2))

  plot(results$power_adj_hc0,ylim = range(c(results$power_adj_hc0,results$power_unadj_hc0,results$power_unadj_cv),na.rm = T),
       col=2,ylab="power",xlab='',main='power')
  lines(results$power_unadj_hc0,type='p',pch=2,col=4)
  lines(results$power_unadj_cv,type='p',pch=2,col=3)
  abline(h=0.05,lty=2)

  legend('bottomright',c('adjusted_hc0','unadj_hc0',"unadj_const"),col=c(2,4,3),pch=c(1,2,2))

  par(mfrow=c(1,1))

}
```

```{r}

xin_raw <- readRDS("data/pancreas/xin_raw.rds")
cell_types = c('alpha', 'beta', 'delta', 'gamma')
K = length(cell_types)
rm.indi = c("Non T2D 4","Non T2D 7","Non T2D 10","Non T2D 12")
rm.indi.idx = which(xin_raw$individual%in%rm.indi)

datax.xin = set_data_decon(Y = xin_raw[,-rm.indi.idx],cell_types = cell_types, gene_thresh = 0.05,max_count_quantile = 0.95,w=1)
design.mat.xin = scRef_multi_proc(datax.xin$Y,datax.xin$cell_type_idx,datax.xin$indi_idx,estimator="separate",est_sigma2 = TRUE,meta_mode = 'local',smooth.sigma = FALSE)

ref = design.mat.xin$X
sigma2 = design.mat.xin$Sigma


G = nrow(ref)
K = 4
# set.seed(12345)
# ref = matrix(rnorm(G*K),nrow=G)
# ref = abs(ref)
# ref = apply(ref, 2, function(z){z/sum(z)})*G
# sigma2 = ref/2
# rownames(ref) = 1:G
b1 = c(0.1,0.1,0.3,0.5)
b2 = c(0.1,0.2,0.5,0.2)
nb = 4
b.m = cbind(b1%*%t(rep(1,nb/2)),b2%*%t(rep(1,nb/2)))

ref = ref+1/nrow(ref)
sigma2 = sigma2 + 1/nrow(ref)
```

```{r}
d = 50
A = matrix(0,nrow=G,ncol=G)

for(i in 1:G){
  for(j in i:min(i+d,G)){
    A[i,j] = max(1-abs(i-j)/d,0)
  }
}
A = A+t(A) - diag(G)
library(Matrix)
A = Matrix(A,sparse = TRUE)
```


## each gene correlated with 50 genes

```{r}
set.seed(12345)
simu = simu_corr_simple(ref,b.m,nreps=100,
                        sigma2=sigma2,
                        R=A,n_indi = 10,
                        verbose = F,
                        printevery = 1)
saveRDS(simu,file='output/simu_correlation_checkavariance_betahat_G10000d50_xin.rds')
# simu = readRDS('output/simu_correlation_checkavariance_betahat_G10000d50.rds')
```

```{r}
ploter.temp(simu)
```

Coverage, adjusted for correlation
```{r}
simu$coverage_adj_hc0
mean(simu$coverage_adj_hc0,na.rm=TRUE)
```

Coverage, not adjusted for correlation
```{r}
simu$coverage_unadj_hc0
mean(simu$coverage_unadj_hc0)
```


Check variance of $\hat p$, estimated proportion

```{r}
par(mfrow=c(1,1))
plot(apply(simu$est_adj,2,sd),type='b',ylim=c(0,0.06))
lines(apply(simu$se_adj_hc0,2,mean,na.rm=T),type='b',col=3)
legend('bottomright',c('true p_hat se','estimated'),lty=c(1,1),pch=c(1,1),col=c(1,3))
```


## each gene correlated with 500 genes

```{r}

# d = 500
# A = matrix(0,nrow=G,ncol=G)
# 
# for(i in 1:G){
#   for(j in i:min(i+d,G)){
#     A[i,j] = max(1-abs(i-j)/d,0)
#   }
# }
# A = A+t(A) - diag(G)
# library(Matrix)
# A = Matrix(A,sparse = TRUE)


# set.seed(12345)
# simu = simu_corr_simple(ref,b.m,nreps=100,
#                         sigma2=sigma2,
#                         R=A,n_indi = 10,
#                         verbose = F,
#                         printevery = 1)
# saveRDS(simu,file='output/simu_correlation_checkavariance_betahat_G10000d500.rds')
simu = readRDS('output/simu_correlation_checkavariance_betahat_G10000d500.rds')
```


```{r}
ploter.temp(simu)
```

Coverage, adjusted for correlation
```{r}
simu$coverage_adj_hc0
mean(simu$coverage_adj_hc0,na.rm=TRUE)
```

Coverage, not adjusted for correlation
```{r}
simu$coverage_unadj_hc0
mean(simu$coverage_unadj_hc0)
```


Check variance of $\hat p$, estimated proportion

```{r}
par(mfrow=c(1,1))
plot(apply(simu$est_adj,2,sd),type='b',ylim=c(0,0.06))
lines(apply(simu$se_adj_hc0,2,mean,na.rm=T),type='b',col=3)
legend('bottomright',c('true p_hat se','estimated'),lty=c(1,1),pch=c(1,1),col=c(1,3))
```
