---
title: "simulation correlation, with estimated correlations"
author: "DongyueXie"
date: "2021-06-21"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction



```{r}
ploter.coverage = function(simu){

  par(mfrow=c(1,2))

  plot(simu$coverage_adj_hc0,
       ylim = range(c(simu$coverage_adj_hc0,
                      simu$coverage_adj_hc2,
                      simu$coverage_adj_hc3,1),na.rm = T),
       col=2,ylab='coverage',xlab='coefs',main='coverage of p',type='b')
  lines(simu$coverage_adj_hc2,type='b',pch=2,col=3)
  lines(simu$coverage_adj_hc3,type='b',pch=3,col=4)
  abline(h=0.95,lty=2)
  
  legend('bottomright',c('cor_adj_hc0','cor_adj_hc2',"cor_adj_hc3"),
         col=c(1,3,4),pch=c(1,2,3))
  
  
  plot(simu$coverage_unadj_hc0,
       ylim = range(c(simu$coverage_unadj_hc0,
                      simu$coverage_unadj_hc2,
                      simu$coverage_unadj_hc3,1),na.rm = T),
       col=2,ylab='coverage',xlab='coefs',main='coverage of p',type='b')
  lines(simu$coverage_unadj_hc2,type='b',pch=2,col=3)
  lines(simu$coverage_unadj_hc3,type='b',pch=3,col=4)
  abline(h=0.95,lty=2)
  
  legend('topright',c('cor_unadj_hc0','cor_unadj_hc2',"cor_unadj_hc3"),
         col=c(1,3,4),pch=c(1,2,3))


  # plot(simu$coverage_diff_adj_hc0,ylim = range(c(simu$coverage_diff_adj_hc0,simu$coverage_diff_unadj_hc0,simu$coverage_diff_unadj_cv,1),na.rm = T),
  #      col=2,type='b',ylab='coverage',xlab='coefs',main='coverage of difference')
  # lines(simu$coverage_diff_unadj_hc0,type='b',pch=2,col=4)
  # lines(simu$coverage_diff_unadj_cv,type='b',pch=2,col=3)
  # abline(h=0.95,lty=2)
  # 
  # #p_order = order(abs(simu$p-simu$p2))
  # 
  # plot(simu$power_adj_hc0,ylim = range(c(simu$power_adj_hc0,simu$power_unadj_hc0,simu$power_unadj_cv),na.rm = T),
  #      col=2,ylab="power",xlab='',main='power')
  # lines(simu$power_unadj_hc0,type='p',pch=2,col=4)
  # lines(simu$power_unadj_cv,type='p',pch=2,col=3)
  # abline(h=0.05,lty=2)
  # 
  # legend('bottomright',c('adjusted_hc0','unadj_hc0',"unadj_const"),col=c(2,4,3),pch=c(1,2,2))
  # 
par(mfrow=c(1,1))

}
```




10 individuals, alpha = 0.1


```{r,fig.width=12,fig.height=6}

# set.seed(12345)
# simu = simu_corr_simple(ref,b.m,nreps=100,
#                         sigma2=sigma2,
#                         R=A,n_indi = 10,
#                         verbose = F,
#                         printevery = 1,
#                         est_cor = TRUE)
# saveRDS(simu,file='output/simu_correlation_checkavariance_betahat_d50_xin_est_cor_10indi.rds')
simu10 = readRDS('output/simu_correlation_checkavariance_betahat_d50_xin_est_cor_10indi.rds')
ploter.coverage(simu10)
```


10 individuals, alpha = 0.3


```{r,fig.width=12,fig.height=6}

# set.seed(12345)
# simu = simu_corr_simple(ref,b.m,nreps=100,
#                         sigma2=sigma2,
#                         R=A,n_indi = 10,
#                         verbose = F,
#                         printevery = 1,
#                         est_cor = TRUE)
# saveRDS(simu,file='output/simu_correlation_checkavariance_betahat_d50_xin_est_cor_10indi.rds')
simu10 = readRDS('output/simu_correlation_checkavariance_betahat_d50_xin_est_cor_10indi_alpha03.rds')
ploter.coverage(simu10)
```

100 individuals, alpha = 0.1


```{r,fig.width=12,fig.height=6}

# set.seed(12345)
# simu = simu_corr_simple(ref,b.m,nreps=100,
#                         sigma2=sigma2,
#                         R=A,n_indi = 100,
#                         verbose = F,
#                         printevery = 1,
#                         est_cor = TRUE)

simu100 = readRDS('output/simu_correlation_checkavariance_betahat_d50_xin_est_cor_100indi.rds')
ploter.coverage(simu100)
```



