---
title: "simulation correlation, with estimated correlations using generated bulk sample"
author: "DongyueXie"
date: "2021-06-21"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

Generate bulk sample for estimating correlations. Proportions of cell type in  bulk samples are randomly smapled from U(0,1) then normalized.

```{r,warning=F,message=F}
source('code/deconference_main.R')
source('code/utils.R')
source('code/wols.R')
source('code/simulation/simu_correlation_ult.R')

ploter.coverage = function(simu){

  par(mfrow=c(1,2))

  plot(simu$coverage_adj_hc0,
       ylim = range(c(simu$coverage_adj_hc0,
                      simu$coverage_adj_hc2,
                      simu$coverage_adj_hc3,1),na.rm = T),
       col=2,ylab='coverage',xlab='coefs',main='coverage of p',type='b')
  lines(simu$coverage_adj_hc2,type='b',pch=2,col=3)
  lines(simu$coverage_adj_hc3,type='b',pch=3,col=4)
  abline(h=0.95,lty=2)
  
  legend('bottomright',c('cor_adj_hc0','cor_adj_hc2',"cor_adj_hc3"),
         col=c(1,3,4),pch=c(1,2,3))
  
  
  plot(simu$coverage_unadj_hc0,
       ylim = range(c(simu$coverage_unadj_hc0,
                      simu$coverage_unadj_hc2,
                      simu$coverage_unadj_hc3,1),na.rm = T),
       col=2,ylab='coverage',xlab='coefs',main='coverage of p',type='b')
  lines(simu$coverage_unadj_hc2,type='b',pch=2,col=3)
  lines(simu$coverage_unadj_hc3,type='b',pch=3,col=4)
  abline(h=0.95,lty=2)
  
  legend('topright',c('cor_unadj_hc0','cor_unadj_hc2',"cor_unadj_hc3"),
         col=c(1,3,4),pch=c(1,2,3))


  # plot(simu$coverage_diff_adj_hc0,ylim = range(c(simu$coverage_diff_adj_hc0,simu$coverage_diff_unadj_hc0,simu$coverage_diff_unadj_cv,1),na.rm = T),
  #      col=2,type='b',ylab='coverage',xlab='coefs',main='coverage of difference')
  # lines(simu$coverage_diff_unadj_hc0,type='b',pch=2,col=4)
  # lines(simu$coverage_diff_unadj_cv,type='b',pch=2,col=3)
  # abline(h=0.95,lty=2)
  # 
  # #p_order = order(abs(simu$p-simu$p2))
  # 
  # plot(simu$power_adj_hc0,ylim = range(c(simu$power_adj_hc0,simu$power_unadj_hc0,simu$power_unadj_cv),na.rm = T),
  #      col=2,ylab="power",xlab='',main='power')
  # lines(simu$power_unadj_hc0,type='p',pch=2,col=4)
  # lines(simu$power_unadj_cv,type='p',pch=2,col=3)
  # abline(h=0.05,lty=2)
  # 
  # legend('bottomright',c('adjusted_hc0','unadj_hc0',"unadj_const"),col=c(2,4,3),pch=c(1,2,2))
  # 
par(mfrow=c(1,1))

}
```



```{r}

xin_raw <- readRDS("data/pancreas/xin_raw.rds")
cell_types = c('alpha', 'beta', 'delta', 'gamma')
K = length(cell_types)
rm.indi = c("Non T2D 4","Non T2D 7","Non T2D 10","Non T2D 12")
rm.indi.idx = which(xin_raw$individual%in%rm.indi)

datax.xin = set_data_decon(Y = xin_raw[,-rm.indi.idx],cell_types = cell_types, 
                           gene_thresh = 0.05,max_count_quantile_celltype = 0.95,
                           max_count_quantile_indi = 0.95,
                           w=1)
design.mat.xin = scRef_multi_proc(datax.xin$Y,datax.xin$cell_type_idx,
                                  datax.xin$indi_idx,estimator="separate",
                                  est_sigma2 = TRUE,meta_mode = 'local',smooth.sigma = F)

ref = design.mat.xin$X
sigma2 = design.mat.xin$Sigma



# set.seed(12345)
# ref = matrix(rnorm(G*K),nrow=G)
# ref = abs(ref)
# ref = apply(ref, 2, function(z){z/sum(z)})*G
# sigma2 = ref/2
# rownames(ref) = 1:G

ref = ref+1/nrow(ref)
sigma2 = sigma2 + 1/nrow(ref)

b1 = c(0.1,0.1,0.3,0.5)
b2 = c(0.1,0.2,0.5,0.2)
nb = 10
b.m = cbind(b1%*%t(rep(1,nb/2)),b2%*%t(rep(1,nb/2)))
```

```{r}
G = nrow(ref)
K = 4
d = 50
A = matrix(0,nrow=G,ncol=G)

for(i in 1:G){
  for(j in i:min(i+d,G)){
    A[i,j] = max(1-abs(i-j)/d,0)
  }
}
A = A+t(A) - diag(G)
library(Matrix)
A = Matrix(A,sparse = TRUE)

dim(ref)
```

100 individuals, alpha = 0.1


```{r,fig.width=12,fig.height=6}

# set.seed(12345)
# simu = simu_corr_simple(ref,b.m,nreps=100,
#                         sigma2=sigma2,
#                         R=A,n_indi = 10,
#                         verbose = F,
#                         printevery = 1,
#                         est_cor = TRUE,
#                         alpha.cor = 0.1,
#                         n_bulk_for_cor = 100)
# saveRDS(simu,'output/simu_correlation_checkavariance_betahat_d50_xin_est_cor_100bulkforcor_alpha01.rds')
simu100 = readRDS('output/simu_correlation_checkavariance_betahat_d50_xin_est_cor_100bulkforcor_alpha01.rds')
ploter.coverage(simu100)
```

100 individuals, alpha = 0.5


```{r,fig.width=12,fig.height=6}

# set.seed(12345)
# simu2 = simu_corr_simple(ref,b.m,nreps=100,
#                         sigma2=sigma2,
#                         R=A,n_indi = 10,
#                         verbose = F, 
#                         printevery = 1,
#                         est_cor = TRUE,
#                         alpha.cor = 0.5,
#                         n_bulk_for_cor = 100)
# saveRDS(simu2,'output/simu_correlation_checkavariance_betahat_d50_xin_est_cor_100bulkforcor_alpha05.rds')
simu100 = readRDS('output/simu_correlation_checkavariance_betahat_d50_xin_est_cor_100bulkforcor_alpha05.rds')
ploter.coverage(simu100)
```



100 individuals, thresholding


```{r,fig.width=12,fig.height=6}

# set.seed(12345)
# simu3 = simu_corr_simple(ref,b.m,nreps=100,
#                         sigma2=sigma2,
#                         R=A,n_indi = 10,
#                         verbose = F,
#                         printevery = 1,
#                         est_cor = TRUE,
#                         alpha.cor = 0.1,
#                         n_bulk_for_cor = 100,
#                         cor_method = 'thresholding')
# saveRDS(simu3,'output/simu_correlation_checkavariance_betahat_d50_xin_est_cor_100bulkforcor_thresh.rds')
simu100 = readRDS('output/simu_correlation_checkavariance_betahat_d50_xin_est_cor_100bulkforcor_thresh.rds')
ploter.coverage(simu100)
```

